# Generated by Django 5.2.9 on 2025-12-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='iframe_url',
            field=models.TextField(max_length=400),
        ),
    ]
