# Generated by Django 5.2.9 on 2026-01-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_iframe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='powerbi_page_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
